# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
    - Verify
    - Package
    - Release

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

Black_Lint:
  stage: Verify
  script:
    - pip install black
    - black . --check

Test:
  stage: Verify
  script:
    - pip install pytest pytest-cov
    - pytest --cov-report xml:coverage.xml --cov=calculator tests/
  artifacts:
    reports:
      cobertura: coverage.xml

Package_sdist:
  stage: Package
  script:
    - pip install setuptools wheel twine
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
