name: Build Pipeline

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: ". --check"
  test:
    needs: [ black-format ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest
      - name: Run Code Coverage Report
        run: |
          pytest --cov=calculator tests/